# Generated by Django 4.0.4 on 2022-11-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bollywoodsubcategory',
            name='BollyWoodCategoryName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homebannerlist',
            name='BannerDiscount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homebannerlist',
            name='BannerSubtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homebannerlist',
            name='BannerTitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='HomeCategoryName',
            field=models.CharField(max_length=200),
        ),
    ]
