# Generated by Django 4.0.4 on 2022-11-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupperUserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductBrandName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(max_length=200),
        ),
    ]
