# Generated by Django 4.0.4 on 2022-11-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupperUserApp', '0002_alter_product_price_alter_product_productbrandname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
