# Generated by Django 4.0.4 on 2022-11-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupperUserApp', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='Payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='orderid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categorylevel1',
            name='CategoryName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categorylevel2',
            name='CategoryLevel2Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categorylevel3',
            name='CategoryLevel3Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='ProductColorName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcolourimage',
            name='ProductImageName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
